### ISSUE TITLE
Vaultwarden: Compatibility Matrix

### ISSUE THREAD

**Issue by diamonwiggins** [replicatedhq/replicated-starter-helm#13]
We should add a working example of using the Compatibility Matrix to the Vaultwarden example in this repo. 

https://docs.google.com/document/d/1ySwaNlokXDsYyYhngRSQCNN6JidFvOnWDXQ-zZdXu2k

**Comment by chris-sanders** [comment]
I'm going to close this issue here, as the new direction is to put all examples in https://github.com/replicatedhq/platform-examples
