### ISSUE TITLE
Document end to end procedure for building a release w/ replicated-library chart and KOTS

### ISSUE THREAD

**Issue by adamancini** [replicatedhq/replicated-starter-helm#8]

**Comment by diamonwiggins** [comment]
We have a working example of this that will be merged with https://github.com/replicatedhq/replicated-starter-helm/pull/11, but we should also ensure that the primary example in this repo, Vaultwarden, is using the same workflow and actively creating new releases on merges to main.

@drohnow a good one to take a look at in the near-term.

**Comment by chris-sanders** [comment]
I'm going to close this issue here, as the new direction is to put all examples in https://github.com/replicatedhq/platform-examples
